services:
  cpp-backend:
    build:
      context: ./weather_app
      dockerfile: Dockerfile
    container_name: cpp_weather_backend
    volumes:
      - bin-share-volume:/app_bin

  fastapi-gateway:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    container_name: fastapi_weather_gateway
    ports:
      - "8000:8000"
    volumes:
      - bin-share-volume:/app_bin
    depends_on:
      - cpp-backend
      
  nginx-server:
    image: nginx:alpine
    container_name: nginx_weather_webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - fastapi-gateway

volumes:
  bin-share-volume: